name: GitHub Actions Vercel Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
    jobs:
      Test:
        uses: salsabildivas/SPEED/.github/workflows/test.yml@develop
        Deploy-Preview:
          runs-on: ubuntu-latest
          needs: [test]
            steps:
              - uses: actions/checkout@v3
              - name: Install Vercel CLI
                run: npm install --global vercel@canary
              - name: Pull Vercel Environment Information
                run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
              - name: Build Project Artifacts
                run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
              - name: Deploy Project Artifacts to Vercel
                run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
                